services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  user-service:
    container_name: user-service
    image: mockserver/mockserver:5.15.0
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/spec.json
      MOCKSERVER_WATCH_INITIALIZATION_JSON: true
    volumes:
      - type: bind
        source: ./mockserver/spec.json
        target: /config/spec.json
volumes:
  postgres_data:
