name: Assign Milestone

on:
  pull_request:
    types: [opened]

jobs:
  assign-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Assign milestone
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const milestones = await github.rest.issues.listMilestones({
              owner,
              repo
            });

            const milestone = milestones.data.find(m => !m.closed_at);
            if (!milestone) {
              console.log("No open milestones found.");
              return;
            }

            await github.rest.issues.update({
              owner,
              repo,
              issue_number: prNumber,
              milestone: milestone.number
            });

            console.log(`Assigned milestone: ${milestone.title} to PR #${prNumber}`);